[service]  
name = "earn_vaults"  

[env]  
DATABASE_URL = "${DATABASE_URL}"  # Load from environment variables  
RAILWAY_TOKEN = "${RAILWAY_TOKEN}"  # Load from environment variables  
API_KEY = "${API_KEY}"  # Load from environment variables  

RAILWAY_ENVIRONMENT = "production"  # Environment Type  
BACKUP_DIR = "./backups"  # Database Backup Directory